### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by wmealing** [progfolio/accord#1]
Gday, 

I tried the demo link today  in the readme and it was not working anymore.  Can you uploads a new screenshot or demo video ?

Thanks !

**Comment by progfolio** [comment]
Wade Mealing ***@***.***> writes:

> Gday,
>
> I tried the demo link today in the readme and it was not working 
> anymore. Can you uploads a
> new screenshot or demo video ?
>
> Thanks !
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this 
> thread.

Thanks for brining this to my attention.
I've updated the link.
